[package]
name = "kiwi-cli"
version = "0.1.0"
description = "🏫 Schoolwork as code"
authors = ["Matt Gleich <email@mattglei.ch>"]
edition = "2018"
repository = "https://github.com/gleich/kiwi/"
homepage = "https://github.com/gleich/kiwi/"
license = "MPL-2.0"
keywords = ["kiwi", "cli", "latex", "markdown"]

[dependencies]
clap = "=3.0.0-beta.2"
toml = "0.5.8"
serde = { version = "1.0.127", features = ["derive"] }
dialoguer = "0.8.0"
anyhow = "1.0.42"
colored = "2.0.0"
chrono = "0.4"
num-traits = "0.2.14"
strum = "0.21.0"
strum_macros = "0.21.0"
handlebars = "4.1.2"
serde_json = "1.0.66"
ordinal = "0.2"
which = "4.2.2"
console = "0.14.1"
walkdir = "2"
duct = "0.13.5"

[[bin]]
name = "kiwi"
path = "src/main.rs"
