#########
# Build #
#########
[tasks.build]
dependencies = ["build-rust", "build-docker"]

[tasks.build-rust]
dependencies = ["build-rust-prod", "build-rust-dev"]

[tasks.build-rust-prod]
command = "cargo"
args = ["build", "--release"]

[tasks.build-rust-dev]
command = "cargo"
args = ["build"]

########
# Test #
########
[tasks.test]
dependencies = ["test-rust"]

[tasks.test-rust]
command = "cargo"
args = ["test"]

########
# Lint #
########
[tasks.lint]
dependencies = ["lint-rust", "lint-dockerfiles"]

[tasks.lint-rust]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
